[package]
name = "rbom"
version = "0.2.0"
edition = "2021"

[dependencies]
binary-parser = {git = "https://github.com/jernejstrasner/binary-parser", version = "0.3.0"}
log = "0.4.14"
env_logger = "0.10.0"
